[tool.poetry]
name = "onnx2kerastl"
version = "0.0.37"
description = ""
authors = ["dorhar <doron.harnoy@tensorleap.ai>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
tensorflow = "^2.8"
tensorflow-addons = "^0.16.1"
onnx = "^1.11.0"
keras-data-format-converter = "0.0.12"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
torch = "^1.11.0"
torchvision = "^0.12.0"
keras-data-format-converter = "0.0.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
